---
  extends:
    - plugin:react/recommended
    - airbnb


  env:
    browser: true
    node: true
    es6: true
  parser: babel-eslint
  parserOptions:
   ecmaVersion: 6
   sourceType: "module"
   ecmaFeatures:
    jsx: true

  globals:
    WordCloud: true
    firebase: true
    google: true
    Rx: true
    process.env: true
    __DEV__: true
    __HASHPATH__: true
    __SERVER__: true

  plugins:
    - react

  rules:
    react/prop-types: [1, { ignore: [children] }]
    react/no-string-refs: 0
    react/require-default-props: 0
    react/forbid-prop-types: 0
    linebreak-style: 0
    semi: 0
    no-console: 0
    no-multi-assign: 0