---
  extends:
    - plugin:react/recommended
    - airbnb


  env:
    browser: true
    node: true
    es6: true
  parser: babel-eslint
  parserOptions:
   ecmaVersion: 6
   sourceType: "module"
   ecmaFeatures:
    jsx: true

  globals:
    WordCloud: true
    firebase: true
    google: true
    Rx: true
    process.env: true
    __DEV__: true
    __HASHPATH__: true
    __SERVER__: true

  plugins:
    - react

  rules:
    react/jsx-uses-vars: 1
    react/prop-types: [1, { ignore: [children] }]
    react/no-string-refs: 0
    react/no-array-index-key: 0
    react/require-default-props: 0
    react/forbid-prop-types: 0
    class-methods-use-this: 0
    no-new: 0
    import/no-extraneous-dependencies: 0
    camelcase: 0
    consistent-return: 0
    linebreak-style: 0
    semi: 0
    no-console: 0
    no-multi-assign: 0